name: Deploy Databricks Asset Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This links to the 'Environment' you created in GitHub Settings
    environment: prod 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Validate Databricks bundle
        # Use the path where your databricks.yml is located
        working-directory: .bundle/asset_bundle_demo
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKENS }}
        run: databricks bundle validate --target prod

      - name: Deploy Databricks bundle
        working-directory: .bundle/asset_bundle_demo
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKENS }}
        run: databricks bundle deploy --target prod
